### PR TITLE
Fixed circle.

### PR DESCRIPTION
**Pull request by all19ryo**
I tried to start over but I erased original file by mistake.
So I just a little revised 556 line and 557 line because I want to learn GitHub and make changes.
I'm sorry...

### CODE REVIEW

**Comment by oladhari** [comment]
thank you !

**Comment by oladhari** [comment]
always assign yourself to the issue or the PR that you have been working on
and once you finish working on PR assign the reviewer to the review
Screenshot from 2020-04-02 09-50-59

**Comment by all19ryo** [comment]
OK!
I feel difficult but I gradually came to understand!
Thank you for your kind response.

**Comment by oladhari** [comment]
you are welcome
LGTM -> Looks Good To Me

**Pull request merged**
